name: Build and test

on: [pull_request]

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x, 14.x, 18.x]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - name: install
        run: |
          npm ci

      - name: static checks
        run: |
          npm run lint

      - name: build
        run: |
          npm run build

      - name: test
        run: |
          npm run test
